const list = [
  {
    id: "1",
    category: "Cardiology",
    name: "Emily Baker",
    specialist: "Cardiologist",
    experience: "20",
    img: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=1470&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Baker is a renowned cardiologist who is passionate about heart health. She specializes in diagnosing and treating heart conditions and is committed to helping her patients maintain healthy hearts.",
  },
  {
    id: "2",
    category: "Cardiology",
    name: "Susan Lewis",
    specialist: "Cardiologist",
    experience: "5",
    img: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=1374&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Lewis is a renowned cardiologist who is passionate about heart health. She is committed to preventing and treating heart conditions through advanced cardio logical methods.",
  },
  {
    id: "3",
    category: "Neurology",
    name: "Michael Harris",
    specialist: "Neurologist",
    experience: "7",
    img: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=1470&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Harris is a neurologist with a strong focus on diagnosing and treating neurological disorders, ensuring the best possible care for patients with conditions affecting the brain, spinal cord, and nerves.",
  },
  {
    id: "4",
    category: "Neurology",
    name: "Maria Rodriguez",
    specialist: "Neurologist",
    experience: "3",
    img: "https://images.unsplash.com/photo-1623854767648-e7bb8009f0db?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Rodriguez is a neurologist with a passion for understanding and treating disorders of the nervous system. She provides compassionate care and treatment for patients with neurological conditions.",
  },
  {
    id: "5",
    category: "Dermatology",
    name: "James Mitchell",
    specialist: "Dermatologist",
    experience: "4",
    img: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=1470&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Mitchell is a skilled dermatologist who excels in skin, hair, and nail-related issues. He provides expert advice and treatments to enhance skin health.",
  },
  {
    id: "6",
    category: "Dermatology",
    name: "William Martin",
    specialist: "Dermatologist",
    experience: "3",
    img: "https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&q=80&w=1374&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Martin is a skilled dermatologist specializing in skin, hair, and nail health. He offers a wide range of treatments to enhance and maintain skin wellness.",
  },
  {
    id: "7",
    category: "Otolaryngology",
    name: "Emily Davis",
    specialist: "Otolaryngologist",
    experience: "10",
    img: "https://images.unsplash.com/photo-1643297654416-05795d62e39c?auto=format&fit=crop&q=80&w=1453&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Davis is an ENT specialist with expertise in ear, nose, and throat issues. She provides comprehensive care and treatments for a variety of ENT-related conditions.",
  },
  {
    id: "8",
    category: "Gastroenterology",
    name: "John Collins",
    specialist: "Dermatologist",
    experience: "5",
    img: "https://images.unsplash.com/photo-1622253694242-abeb37a33e97?auto=format&fit=crop&q=80&w=1365&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    bio: "Dr. Collins is a gastroenterologist known for his expertise in digestive system disorders, including the stomach, intestines, and related organs. He focuses on improving gastrointestinal health.",
  },
];

export { list as doctorList };
